# Generated by Django 6.0.4 on 2026-04-25 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypack',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policypack',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policypack',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='policypack',
            name='rollout_percentage',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddIndex(
            model_name='policypack',
            index=models.Index(fields=['effective_from', 'effective_to'], name='policy_poli_effecti_70866f_idx'),
        ),
    ]
