# Generated by Django 6.0.4 on 2026-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0002_policypack_effective_from_policypack_effective_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policypack",
            name="allowed_exceptions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="policypack",
            name="media_thresholds",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="policypack",
            name="provider_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
