# Generated by Django 6.0.4 on 2026-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(default='global', max_length=16)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['region_code', 'enabled'], name='ads_adslotc_region__2630c7_idx')],
            },
        ),
    ]
