# Generated by Django 6.0.4 on 2026-04-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('region_code', models.CharField(default='global', max_length=16)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=16)),
                ('ad_event_key', models.CharField(max_length=120)),
                ('placement', models.CharField(default='feed', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='ads_addeliv_event_t_30e070_idx'), models.Index(fields=['ad_event_key', 'created_at'], name='ads_addeliv_ad_even_09663f_idx'), models.Index(fields=['region_code', 'created_at'], name='ads_addeliv_region__e18842_idx')],
            },
        ),
    ]
