# Generated by Django 6.0.4 on 2026-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.PositiveBigIntegerField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('policy_region', models.CharField(db_index=True, max_length=16)),
                ('policy_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
