# Generated by Django 6.0.4 on 2026-05-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderationflag_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationflag',
            name='apply_penalty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moderationflag',
            name='reporter_user_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationflag',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='moderationflag',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationflag',
            name='reviewed_by_user_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationflag',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='moderationflag',
            name='target_user_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ModerationPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('reason_type', models.CharField(choices=[('content_violation', 'Content Violation'), ('false_report', 'False Report')], max_length=32)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('removed_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='moderation.moderationflag')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'active', 'expires_at'], name='moderation__user_id_130fdd_idx'), models.Index(fields=['reason_type', 'active', 'expires_at'], name='moderation__reason__fc27f2_idx')],
            },
        ),
    ]
