# Generated by Django 6.0.4 on 2026-04-25 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('algorithm_profile_status', models.CharField(choices=[('not_started', 'Not started'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_started', max_length=32)),
                ('algorithm_vector', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
