# Generated by Django 6.0.4 on 2026-04-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_ranking_fields_and_action_scores'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profileactionscore',
            new_name='accounts_pr_profile_cd7abf_idx',
            old_name='accounts_pr_profile_a34fd8_idx',
        ),
        migrations.RenameIndex(
            model_name='profileactionscore',
            new_name='accounts_pr_profile_c17a11_idx',
            old_name='accounts_pr_profile_14f77b_idx',
        ),
    ]
