# Generated by Django 6.0.4 on 2026-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sitesetting_signupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allowed_signup_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='restrict_signup_countries',
            field=models.BooleanField(default=False),
        ),
    ]
