# Generated by Django 6.0.4 on 2026-04-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sitesetting_allowed_signup_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='restrict_signup_countries',
        ),
    ]
