# Generated by Django 6.0.4 on 2026-04-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_sitesetting_restrict_signup_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allow_signup_on_ip_country_lookup_failure',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_backend',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_timeout_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_use_ssl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_use_tls',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enforce_signup_ip_country_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='frontend_base_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ip_country_lookup_timeout_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ip_country_lookup_url_template',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
