# Generated by Django 6.0.4 on 2026-04-25 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('like', 'Like'), ('reply', 'Reply'), ('repost', 'Repost'), ('quote', 'Quote'), ('bookmark', 'Bookmark'), ('report', 'Report')], max_length=24)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'action_type'], name='posts_posti_post_id_2569f4_idx'), models.Index(fields=['user', 'action_type'], name='posts_posti_user_id_2d34a1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('action_type__in', ['like', 'bookmark', 'repost', 'report'])), fields=('post', 'user', 'action_type'), name='unique_singleton_interaction_per_user_action')],
            },
        ),
    ]
