# Generated by Django 6.0.4 on 2026-04-25 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_preview',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='media_url',
            field=models.URLField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
