# Generated by Django 6.0.4 on 2026-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_link_preview_alter_mediaattachment_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreviewCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('host', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(default='fallback', max_length=24)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'expires_at'], name='posts_linkp_host_8303e3_idx')],
            },
        ),
    ]
