# Generated by Django 6.0.4 on 2026-04-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_idempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='conflict_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='last_replayed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='replay_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
