# Generated by Django 6.0.4 on 2026-04-25 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_idempotencyrecord_conflict_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncReplayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('client', 'Client'), ('service_worker', 'Service Worker')], max_length=24)),
                ('kind', models.CharField(max_length=32)),
                ('endpoint', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('dropped', 'Dropped'), ('retry', 'Retry')], max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('replayed_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_replay_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'outcome', '-replayed_at'], name='posts_syncr_user_id_2f8593_idx'), models.Index(fields=['source', 'kind', '-replayed_at'], name='posts_syncr_source_221205_idx')],
            },
        ),
    ]
