# Generated by Django 6.0.4 on 2026-04-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_sentiment_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_parent__91361c_idx',
            old_name='posts_post_parent__f0ee0c_idx',
        ),
    ]
