# Generated by Django 6.0.4 on 2026-05-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_mediaattachment_metadata_uploadedmediaasset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uploadedmediaasset',
            new_name='posts_uploa_user_id_19d3c3_idx',
            old_name='posts_uploa_user_id_7096d4_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedmediaasset',
            new_name='posts_uploa_user_id_7921d0_idx',
            old_name='posts_uploa_user_id_89f466_idx',
        ),
    ]
