# Generated by Django 6.0.4 on 2026-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_rename_posts_uploa_user_id_7096d4_idx_posts_uploa_user_id_19d3c3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="analysis_blocked_categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="analysis_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="analysis_fingerprint",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="post",
            name="analysis_modules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="post",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("approved", "Approved"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="analysis_terms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="analysis_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="post",
            name="needs_analysis_refresh",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="analysis_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="analysis_fingerprint",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("approved", "Approved"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="delta_rank_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postinteraction",
            name="inherited_rank_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_fingerprint",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_model_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_provider",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("approved", "Approved"),
                    ("blocked", "Blocked"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_terms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="analysis_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="is_artwork_source",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="is_video_game_capture",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadedmediaasset",
            name="needs_analysis_refresh",
            field=models.BooleanField(default=True),
        ),
    ]
