# Generated by Django 6.0.4 on 2026-05-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_feed_profile_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_parent__4310dd_idx',
            old_name='posts_parent_vis_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_author__98c3c2_idx',
            old_name='posts_author_parent_pinned_idx',
        ),
    ]
