from .base import *  # noqa: F403,F401

DEBUG = True
ALLOWED_HOSTS = ["*"]
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
UNITE_ALLOW_LOCAL_DEMO_RESET = True
UNITE_SENTIMENT_LOCAL_FILES_ONLY = True
