# Generated by Django 6.0.4 on 2026-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_interval', models.PositiveIntegerField(default=3)),
                ('ad_interval', models.PositiveIntegerField(default=0)),
                ('suggestions_enabled', models.BooleanField(default=True)),
                ('ads_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
